//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.aaancnuit.com.AAANCNU_Common_version2", ClrNamespace="www.aaancnuit.com.aaancnu_common_version2")]

namespace IDP
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_WSDL_IssueDirectPayment_version2", ConfigurationName = "IssueDirectPayment")]
    public interface IssueDirectPayment
    {

        // CODEGEN: Generating message contract since the operation IssueDirectPayment is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.aaancnuit.com.issueDirectPayment", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.aaancnuit.com.aaancnu_common_version2.ErrorInfo), Action = "http://www.aaancnuit.com.issueDirectPayment", Name = "ErrorInfo", Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ErrorInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PolicySource))]
        IssueDirectPaymentResponse1 IssueDirectPayment(IssueDirectPaymentRequest1 request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_WSDL_IssueDirectPayment_version2")]
    public partial class issueDirectPaymentRequest
    {

        private ApplicationContext applicationContextField;

        private string externalReferenceNumberField;

        private string agentIdentifierField;

        private string agencyField;

        private string clubField;

        private string userIdField;

        private string branchHubNumberField;

        private string districtOfficeField;

        private string deviceNumberField;

        private string authenticationChannelField;

        private decimal totalAmountField;

        private bool totalAmountFieldSpecified;

        private string sourcePhoneNumberField;

        private LineItems lineItemsField;

        private PaymentItems paymentItemsField;

        private string emailToField;

        private object[] messageExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ApplicationContext applicationContext
        {
            get
            {
                return this.applicationContextField;
            }
            set
            {
                this.applicationContextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string externalReferenceNumber
        {
            get
            {
                return this.externalReferenceNumberField;
            }
            set
            {
                this.externalReferenceNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string agentIdentifier
        {
            get
            {
                return this.agentIdentifierField;
            }
            set
            {
                this.agentIdentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string agency
        {
            get
            {
                return this.agencyField;
            }
            set
            {
                this.agencyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string club
        {
            get
            {
                return this.clubField;
            }
            set
            {
                this.clubField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string branchHubNumber
        {
            get
            {
                return this.branchHubNumberField;
            }
            set
            {
                this.branchHubNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string districtOffice
        {
            get
            {
                return this.districtOfficeField;
            }
            set
            {
                this.districtOfficeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string deviceNumber
        {
            get
            {
                return this.deviceNumberField;
            }
            set
            {
                this.deviceNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string authenticationChannel
        {
            get
            {
                return this.authenticationChannelField;
            }
            set
            {
                this.authenticationChannelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public decimal totalAmount
        {
            get
            {
                return this.totalAmountField;
            }
            set
            {
                this.totalAmountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalAmountSpecified
        {
            get
            {
                return this.totalAmountFieldSpecified;
            }
            set
            {
                this.totalAmountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string sourcePhoneNumber
        {
            get
            {
                return this.sourcePhoneNumberField;
            }
            set
            {
                this.sourcePhoneNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public LineItems lineItems
        {
            get
            {
                return this.lineItemsField;
            }
            set
            {
                this.lineItemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public PaymentItems paymentItems
        {
            get
            {
                return this.paymentItemsField;
            }
            set
            {
                this.paymentItemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public string emailTo
        {
            get
            {
                return this.emailToField;
            }
            set
            {
                this.emailToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageExtension", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        public object[] messageExtension
        {
            get
            {
                return this.messageExtensionField;
            }
            set
            {
                this.messageExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class ApplicationContext
    {

        private string userIdField;

        private string transactionTypeField;

        private string applicationField;

        private string subSystemField;

        private string addressField;

        private string correlationIdField;

        private object[] applicationContextExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string transactionType
        {
            get
            {
                return this.transactionTypeField;
            }
            set
            {
                this.transactionTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string subSystem
        {
            get
            {
                return this.subSystemField;
            }
            set
            {
                this.subSystemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string correlationId
        {
            get
            {
                return this.correlationIdField;
            }
            set
            {
                this.correlationIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("applicationContextExtension", Order = 6)]
        public object[] applicationContextExtension
        {
            get
            {
                return this.applicationContextExtensionField;
            }
            set
            {
                this.applicationContextExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class ErrorInfo
    {

        private System.DateTime errorTimeStampField;

        private bool errorTimeStampFieldSpecified;

        private string errorCodeField;

        private string severityField;

        private string errorMessageTextField;

        private string friendlyErrorMessageField;

        private string vendorMessageTextField;

        private string stackTraceField;

        private string sqlStateField;

        private string serviceNameField;

        private string sourceSystemField;

        private RuleResponses ruleResponseField;

        private object[] errorInfoExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public System.DateTime errorTimeStamp
        {
            get
            {
                return this.errorTimeStampField;
            }
            set
            {
                this.errorTimeStampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorTimeStampSpecified
        {
            get
            {
                return this.errorTimeStampFieldSpecified;
            }
            set
            {
                this.errorTimeStampFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string errorMessageText
        {
            get
            {
                return this.errorMessageTextField;
            }
            set
            {
                this.errorMessageTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string friendlyErrorMessage
        {
            get
            {
                return this.friendlyErrorMessageField;
            }
            set
            {
                this.friendlyErrorMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string vendorMessageText
        {
            get
            {
                return this.vendorMessageTextField;
            }
            set
            {
                this.vendorMessageTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string stackTrace
        {
            get
            {
                return this.stackTraceField;
            }
            set
            {
                this.stackTraceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string sqlState
        {
            get
            {
                return this.sqlStateField;
            }
            set
            {
                this.sqlStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string serviceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string sourceSystem
        {
            get
            {
                return this.sourceSystemField;
            }
            set
            {
                this.sourceSystemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public RuleResponses ruleResponse
        {
            get
            {
                return this.ruleResponseField;
            }
            set
            {
                this.ruleResponseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errorInfoExtension", Order = 11)]
        public object[] errorInfoExtension
        {
            get
            {
                return this.errorInfoExtensionField;
            }
            set
            {
                this.errorInfoExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class RuleResponses
    {

        private RuleResponse[] ruleResponseField;

        private object[] ruleResponsesExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleResponse", Order = 0)]
        public RuleResponse[] ruleResponse
        {
            get
            {
                return this.ruleResponseField;
            }
            set
            {
                this.ruleResponseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleResponsesExtension", Order = 1)]
        public object[] ruleResponsesExtension
        {
            get
            {
                return this.ruleResponsesExtensionField;
            }
            set
            {
                this.ruleResponsesExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class RuleResponse
    {

        private System.DateTime timestampField;

        private bool timestampFieldSpecified;

        private string ruleDecisionField;

        private string ruleScoreField;

        private string serviceField;

        private string[] ruleScorecardField;

        private RuleResult ruleResultsField;

        private object[] ruleResponseExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified
        {
            get
            {
                return this.timestampFieldSpecified;
            }
            set
            {
                this.timestampFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ruleDecision
        {
            get
            {
                return this.ruleDecisionField;
            }
            set
            {
                this.ruleDecisionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string ruleScore
        {
            get
            {
                return this.ruleScoreField;
            }
            set
            {
                this.ruleScoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleScorecard", Order = 4)]
        public string[] ruleScorecard
        {
            get
            {
                return this.ruleScorecardField;
            }
            set
            {
                this.ruleScorecardField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public RuleResult ruleResults
        {
            get
            {
                return this.ruleResultsField;
            }
            set
            {
                this.ruleResultsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleResponseExtension", Order = 6)]
        public object[] ruleResponseExtension
        {
            get
            {
                return this.ruleResponseExtensionField;
            }
            set
            {
                this.ruleResponseExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class RuleResult
    {

        private string ruleIdField;

        private string ruleDescriptionField;

        private string actionField;

        private RuleSeverity severityField;

        private bool severityFieldSpecified;

        private bool isOverridableField;

        private bool isOverridableFieldSpecified;

        private string overrideAuthorityLevelField;

        private string instanceIdField;

        private string sourceSystemField;

        private System.DateTime timestampField;

        private bool timestampFieldSpecified;

        private RuleCategory categoryField;

        private bool categoryFieldSpecified;

        private string correlationIdField;

        private RuleAttribute ruleattributesField;

        private object[] ruleResultExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string ruleId
        {
            get
            {
                return this.ruleIdField;
            }
            set
            {
                this.ruleIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ruleDescription
        {
            get
            {
                return this.ruleDescriptionField;
            }
            set
            {
                this.ruleDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public RuleSeverity severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool severitySpecified
        {
            get
            {
                return this.severityFieldSpecified;
            }
            set
            {
                this.severityFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public bool isOverridable
        {
            get
            {
                return this.isOverridableField;
            }
            set
            {
                this.isOverridableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isOverridableSpecified
        {
            get
            {
                return this.isOverridableFieldSpecified;
            }
            set
            {
                this.isOverridableFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string overrideAuthorityLevel
        {
            get
            {
                return this.overrideAuthorityLevelField;
            }
            set
            {
                this.overrideAuthorityLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 6)]
        public string instanceId
        {
            get
            {
                return this.instanceIdField;
            }
            set
            {
                this.instanceIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string sourceSystem
        {
            get
            {
                return this.sourceSystemField;
            }
            set
            {
                this.sourceSystemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified
        {
            get
            {
                return this.timestampFieldSpecified;
            }
            set
            {
                this.timestampFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public RuleCategory category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categorySpecified
        {
            get
            {
                return this.categoryFieldSpecified;
            }
            set
            {
                this.categoryFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 10)]
        public string correlationId
        {
            get
            {
                return this.correlationIdField;
            }
            set
            {
                this.correlationIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public RuleAttribute ruleattributes
        {
            get
            {
                return this.ruleattributesField;
            }
            set
            {
                this.ruleattributesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleResultExtension", Order = 12)]
        public object[] ruleResultExtension
        {
            get
            {
                return this.ruleResultExtensionField;
            }
            set
            {
                this.ruleResultExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public enum RuleSeverity
    {

        /// <remarks/>
        Informational,

        /// <remarks/>
        High,

        /// <remarks/>
        Medium,

        /// <remarks/>
        Low,

        /// <remarks/>
        Error,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public enum RuleCategory
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Product Constraint")]
        ProductConstraint,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Mandatory Data")]
        MandatoryData,

        /// <remarks/>
        Eligibility,

        /// <remarks/>
        Underwriting,

        /// <remarks/>
        Informational,

        /// <remarks/>
        Clerical,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class RuleAttribute
    {

        private string[] stringRefField;

        private object[] ruleAttributeExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stringRef", Order = 0)]
        public string[] stringRef
        {
            get
            {
                return this.stringRefField;
            }
            set
            {
                this.stringRefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleAttributeExtension", Order = 1)]
        public object[] ruleAttributeExtension
        {
            get
            {
                return this.ruleAttributeExtensionField;
            }
            set
            {
                this.ruleAttributeExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_IssueDirectPayment_version2")]
    public partial class LineItems
    {

        private LineItem[] lineItemField;

        private object[] lineItemsExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lineItem", Order = 0)]
        public LineItem[] lineItem
        {
            get
            {
                return this.lineItemField;
            }
            set
            {
                this.lineItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lineItemsExtension", Order = 1)]
        public object[] lineItemsExtension
        {
            get
            {
                return this.lineItemsExtensionField;
            }
            set
            {
                this.lineItemsExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_IssueDirectPayment_version2")]
    public partial class LineItem
    {

        private string sequenceNumberField;

        private string billingAccountIdField;

        private decimal amountField;

        private bool amountFieldSpecified;

        private string amountForField;

        private bool isCashSweepField;

        private PolicyProductSource policyInfoField;

        private object[] lineItemExtensionField;

        public LineItem()
        {
            this.isCashSweepField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
        public string sequenceNumber
        {
            get
            {
                return this.sequenceNumberField;
            }
            set
            {
                this.sequenceNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string billingAccountId
        {
            get
            {
                return this.billingAccountIdField;
            }
            set
            {
                this.billingAccountIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public decimal amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string amountFor
        {
            get
            {
                return this.amountForField;
            }
            set
            {
                this.amountForField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool isCashSweep
        {
            get
            {
                return this.isCashSweepField;
            }
            set
            {
                this.isCashSweepField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public PolicyProductSource policyInfo
        {
            get
            {
                return this.policyInfoField;
            }
            set
            {
                this.policyInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lineItemExtension", Order = 6)]
        public object[] lineItemExtension
        {
            get
            {
                return this.lineItemExtensionField;
            }
            set
            {
                this.lineItemExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_IssueDirectPayment_version2")]
    public partial class PolicyProductSource : PolicySource
    {

        private string writingCompanyField;

        private string lineOfBusinessField;

        private string typeField;

        private string policyPrefixField;

        private string zipCodeField;

        private object[] policyProductSourceExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string writingCompany
        {
            get
            {
                return this.writingCompanyField;
            }
            set
            {
                this.writingCompanyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string lineOfBusiness
        {
            get
            {
                return this.lineOfBusinessField;
            }
            set
            {
                this.lineOfBusinessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string policyPrefix
        {
            get
            {
                return this.policyPrefixField;
            }
            set
            {
                this.policyPrefixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string zipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("policyProductSourceExtension", Order = 5)]
        public object[] policyProductSourceExtension
        {
            get
            {
                return this.policyProductSourceExtensionField;
            }
            set
            {
                this.policyProductSourceExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolicyProductSource))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_IssueDirectPayment_version2")]
    public partial class PolicySource
    {

        private string policyNumberField;

        private string productCodeField;

        private string riskStateField;

        private string dataSourceField;

        private object[] policySourceExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string policyNumber
        {
            get
            {
                return this.policyNumberField;
            }
            set
            {
                this.policyNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string productCode
        {
            get
            {
                return this.productCodeField;
            }
            set
            {
                this.productCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string riskState
        {
            get
            {
                return this.riskStateField;
            }
            set
            {
                this.riskStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string dataSource
        {
            get
            {
                return this.dataSourceField;
            }
            set
            {
                this.dataSourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("policySourceExtension", Order = 4)]
        public object[] policySourceExtension
        {
            get
            {
                return this.policySourceExtensionField;
            }
            set
            {
                this.policySourceExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_IssueDirectPayment_version2")]
    public partial class PaymentAccount
    {

        private string typeField;

        private string aBANumberField;

        private string routingNumberField;

        private string accountNumberField;

        private string accountHolderNameField;

        private object[] paymentAccountExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ABANumber
        {
            get
            {
                return this.aBANumberField;
            }
            set
            {
                this.aBANumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string routingNumber
        {
            get
            {
                return this.routingNumberField;
            }
            set
            {
                this.routingNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string accountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string accountHolderName
        {
            get
            {
                return this.accountHolderNameField;
            }
            set
            {
                this.accountHolderNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("paymentAccountExtension", Order = 5)]
        public object[] paymentAccountExtension
        {
            get
            {
                return this.paymentAccountExtensionField;
            }
            set
            {
                this.paymentAccountExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_IssueDirectPayment_version2")]
    public partial class CardAuthorization
    {

        private string returnCodeField;

        private string authorizationCodeField;

        private string actualMessageField;

        private string requestIdField;

        private bool isAuthorizedField;

        private bool isInvalidCardField;

        private bool isInvalidDataField;

        private bool isRequestSuccessfulField;

        private object[] cardAuthorizationExtensionField;

        public CardAuthorization()
        {
            this.isAuthorizedField = true;
            this.isInvalidCardField = false;
            this.isInvalidDataField = false;
            this.isRequestSuccessfulField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string returnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string authorizationCode
        {
            get
            {
                return this.authorizationCodeField;
            }
            set
            {
                this.authorizationCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string actualMessage
        {
            get
            {
                return this.actualMessageField;
            }
            set
            {
                this.actualMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string requestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool isAuthorized
        {
            get
            {
                return this.isAuthorizedField;
            }
            set
            {
                this.isAuthorizedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool isInvalidCard
        {
            get
            {
                return this.isInvalidCardField;
            }
            set
            {
                this.isInvalidCardField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool isInvalidData
        {
            get
            {
                return this.isInvalidDataField;
            }
            set
            {
                this.isInvalidDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool isRequestSuccessful
        {
            get
            {
                return this.isRequestSuccessfulField;
            }
            set
            {
                this.isRequestSuccessfulField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cardAuthorizationExtension", Order = 8)]
        public object[] cardAuthorizationExtension
        {
            get
            {
                return this.cardAuthorizationExtensionField;
            }
            set
            {
                this.cardAuthorizationExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_IssueDirectPayment_version2")]
    public partial class PaymentCard
    {

        private string numberField;

        private string typeField;

        private string printedNameField;

        private System.DateTime expirationDateField;

        private bool expirationDateFieldSpecified;

        private string cavvField;

        private string zipCodeField;

        private string merchantIdField;

        private string posEntryModeField;

        private string posTerminalField;

        private string faceToFaceTransactionField;

        private bool isCardPresentField;

        private bool isCardPresentFieldSpecified;

        private CardAuthorization paymentAuthorizationField;

        private object[] paymentCardExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string printedName
        {
            get
            {
                return this.printedNameField;
            }
            set
            {
                this.printedNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 3)]
        public System.DateTime expirationDate
        {
            get
            {
                return this.expirationDateField;
            }
            set
            {
                this.expirationDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expirationDateSpecified
        {
            get
            {
                return this.expirationDateFieldSpecified;
            }
            set
            {
                this.expirationDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string cavv
        {
            get
            {
                return this.cavvField;
            }
            set
            {
                this.cavvField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string zipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string merchantId
        {
            get
            {
                return this.merchantIdField;
            }
            set
            {
                this.merchantIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string posEntryMode
        {
            get
            {
                return this.posEntryModeField;
            }
            set
            {
                this.posEntryModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string posTerminal
        {
            get
            {
                return this.posTerminalField;
            }
            set
            {
                this.posTerminalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string faceToFaceTransaction
        {
            get
            {
                return this.faceToFaceTransactionField;
            }
            set
            {
                this.faceToFaceTransactionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public bool isCardPresent
        {
            get
            {
                return this.isCardPresentField;
            }
            set
            {
                this.isCardPresentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isCardPresentSpecified
        {
            get
            {
                return this.isCardPresentFieldSpecified;
            }
            set
            {
                this.isCardPresentFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public CardAuthorization paymentAuthorization
        {
            get
            {
                return this.paymentAuthorizationField;
            }
            set
            {
                this.paymentAuthorizationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("paymentCardExtension", Order = 12)]
        public object[] paymentCardExtension
        {
            get
            {
                return this.paymentCardExtensionField;
            }
            set
            {
                this.paymentCardExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_IssueDirectPayment_version2")]
    public partial class PaymentItem
    {

        private string paymentMethodField;

        private decimal amountField;

        private bool amountFieldSpecified;

        private string paymentAccountTokenField;

        private string typeField;

        private string statusField;

        private string memoField;

        private string checkNumberField;

        private System.DateTime postmarkDateField;

        private bool postmarkDateFieldSpecified;

        private PaymentCard cardField;

        private PaymentAccount accountField;

        private object[] paymentItemExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string paymentMethod
        {
            get
            {
                return this.paymentMethodField;
            }
            set
            {
                this.paymentMethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public decimal amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string paymentAccountToken
        {
            get
            {
                return this.paymentAccountTokenField;
            }
            set
            {
                this.paymentAccountTokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string memo
        {
            get
            {
                return this.memoField;
            }
            set
            {
                this.memoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string checkNumber
        {
            get
            {
                return this.checkNumberField;
            }
            set
            {
                this.checkNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 7)]
        public System.DateTime postmarkDate
        {
            get
            {
                return this.postmarkDateField;
            }
            set
            {
                this.postmarkDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool postmarkDateSpecified
        {
            get
            {
                return this.postmarkDateFieldSpecified;
            }
            set
            {
                this.postmarkDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public PaymentCard card
        {
            get
            {
                return this.cardField;
            }
            set
            {
                this.cardField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public PaymentAccount account
        {
            get
            {
                return this.accountField;
            }
            set
            {
                this.accountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("paymentItemExtension", Order = 10)]
        public object[] paymentItemExtension
        {
            get
            {
                return this.paymentItemExtensionField;
            }
            set
            {
                this.paymentItemExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_IssueDirectPayment_version2")]
    public partial class PaymentItems
    {

        private PaymentItem[] paymentItemField;

        private object[] paymentItemsExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("paymentItem", Order = 0)]
        public PaymentItem[] paymentItem
        {
            get
            {
                return this.paymentItemField;
            }
            set
            {
                this.paymentItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("paymentItemsExtension", Order = 1)]
        public object[] paymentItemsExtension
        {
            get
            {
                return this.paymentItemsExtensionField;
            }
            set
            {
                this.paymentItemsExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_WSDL_IssueDirectPayment_version2")]
    public partial class issueDirectPaymentResponse
    {

        private ApplicationContext applicationContextField;

        private string externalReferenceNumberField;

        private string receiptNumberField;

        private string statusField;

        private string statusDescriptionField;

        private System.DateTime paymentDateTimeField;

        private bool paymentDateTimeFieldSpecified;

        private PaymentItems paymentItemsField;

        private object[] messageExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ApplicationContext applicationContext
        {
            get
            {
                return this.applicationContextField;
            }
            set
            {
                this.applicationContextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string externalReferenceNumber
        {
            get
            {
                return this.externalReferenceNumberField;
            }
            set
            {
                this.externalReferenceNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string receiptNumber
        {
            get
            {
                return this.receiptNumberField;
            }
            set
            {
                this.receiptNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string statusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public System.DateTime paymentDateTime
        {
            get
            {
                return this.paymentDateTimeField;
            }
            set
            {
                this.paymentDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentDateTimeSpecified
        {
            get
            {
                return this.paymentDateTimeFieldSpecified;
            }
            set
            {
                this.paymentDateTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public PaymentItems paymentItems
        {
            get
            {
                return this.paymentItemsField;
            }
            set
            {
                this.paymentItemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageExtension", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public object[] messageExtension
        {
            get
            {
                return this.messageExtensionField;
            }
            set
            {
                this.messageExtensionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class IssueDirectPaymentRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_WSDL_IssueDirectPayment_version2", Order = 0)]
        public issueDirectPaymentRequest issueDirectPaymentRequest;

        public IssueDirectPaymentRequest1()
        {
        }

        public IssueDirectPaymentRequest1(issueDirectPaymentRequest issueDirectPaymentRequest)
        {
            this.issueDirectPaymentRequest = issueDirectPaymentRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class IssueDirectPaymentResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_WSDL_IssueDirectPayment_version2", Order = 0)]
        public issueDirectPaymentResponse issueDirectPaymentResponse;

        public IssueDirectPaymentResponse1()
        {
        }

        public IssueDirectPaymentResponse1(issueDirectPaymentResponse issueDirectPaymentResponse)
        {
            this.issueDirectPaymentResponse = issueDirectPaymentResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IssueDirectPaymentChannel : IssueDirectPayment, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IssueDirectPaymentClient : System.ServiceModel.ClientBase<IssueDirectPayment>, IssueDirectPayment
    {

        public IssueDirectPaymentClient()
        {
        }

        public IssueDirectPaymentClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public IssueDirectPaymentClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public IssueDirectPaymentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public IssueDirectPaymentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IssueDirectPaymentResponse1 IssueDirectPayment.IssueDirectPayment(IssueDirectPaymentRequest1 request)
        {
            return base.Channel.IssueDirectPayment(request);
        }

        public issueDirectPaymentResponse IssueDirectPayment(issueDirectPaymentRequest issueDirectPaymentRequest)
        {
            IssueDirectPaymentRequest1 inValue = new IssueDirectPaymentRequest1();
            inValue.issueDirectPaymentRequest = issueDirectPaymentRequest;
            IssueDirectPaymentResponse1 retVal = ((IssueDirectPayment)(this)).IssueDirectPayment(inValue);
            return retVal.issueDirectPaymentResponse;
        }
    }
    namespace www.aaancnuit.com.aaancnu_common_version2
    {


        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
        [System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
        public partial class ErrorInfo : object, System.Xml.Serialization.IXmlSerializable
        {

            private System.Xml.XmlNode[] nodesField;

            private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ErrorInfo", "http://www.aaancnuit.com.AAANCNU_Common_version2");

            public System.Xml.XmlNode[] Nodes
            {
                get
                {
                    return this.nodesField;
                }
                set
                {
                    this.nodesField = value;
                }
            }

            public void ReadXml(System.Xml.XmlReader reader)
            {
                this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
            }

            public void WriteXml(System.Xml.XmlWriter writer)
            {
                System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
            }

            public System.Xml.Schema.XmlSchema GetSchema()
            {
                return null;
            }

            public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
            {
                System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
                return typeName;
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
        [System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
        public partial class RuleResponses : object, System.Xml.Serialization.IXmlSerializable
        {

            private System.Xml.XmlNode[] nodesField;

            private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("RuleResponses", "http://www.aaancnuit.com.AAANCNU_Common_version2");

            public System.Xml.XmlNode[] Nodes
            {
                get
                {
                    return this.nodesField;
                }
                set
                {
                    this.nodesField = value;
                }
            }

            public void ReadXml(System.Xml.XmlReader reader)
            {
                this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
            }

            public void WriteXml(System.Xml.XmlWriter writer)
            {
                System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
            }

            public System.Xml.Schema.XmlSchema GetSchema()
            {
                return null;
            }

            public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
            {
                System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
                return typeName;
            }
        }
    }
}
