//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4234
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace RecordBanknameRetrieval
{
    [assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.aaancnuit.com.AAANCNU_Common_version2", ClrNamespace = "www.aaancnuit.com.aaancnu_common_version2")]



    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_WSDL_RetrieveFinancialInstitutionDetail_version2" +
        "", ConfigurationName = "RetrieveFinancialInstitutionDetail")]
    public interface RetrieveFinancialInstitutionDetail
    {

        // CODEGEN: Generating message contract since the operation RetrieveFinancialInstitutionDetail is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.aaancnuit.com.retrieveFinancialInstitutionDetail", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.aaancnuit.com.aaancnu_common_version2.ErrorInfo), Action = "http://www.aaancnuit.com.retrieveFinancialInstitutionDetail", Name = "ErrorInfo", Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ErrorInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RuleResponses))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Institution))]
        RetrieveFinancialInstitutionDetailResponse1 RetrieveFinancialInstitutionDetail(RetrieveFinancialInstitutionDetailRequest1 request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_WSDL_RetrieveFinancialInstitutionDetail_version2" +
        "")]
    public partial class retrieveFinancialInstitutionDetailRequest
    {

        private ApplicationContext applicationContextField;

        private string routingNumberField;

        private object[] messageExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ApplicationContext applicationContext
        {
            get
            {
                return this.applicationContextField;
            }
            set
            {
                this.applicationContextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string routingNumber
        {
            get
            {
                return this.routingNumberField;
            }
            set
            {
                this.routingNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageExtension", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public object[] messageExtension
        {
            get
            {
                return this.messageExtensionField;
            }
            set
            {
                this.messageExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class ApplicationContext
    {

        private string userIdField;

        private string transactionTypeField;

        private string applicationField;

        private string subSystemField;

        private string addressField;

        private string correlationIdField;

        private object[] applicationContextExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string transactionType
        {
            get
            {
                return this.transactionTypeField;
            }
            set
            {
                this.transactionTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string subSystem
        {
            get
            {
                return this.subSystemField;
            }
            set
            {
                this.subSystemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string correlationId
        {
            get
            {
                return this.correlationIdField;
            }
            set
            {
                this.correlationIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("applicationContextExtension", Order = 6)]
        public object[] applicationContextExtension
        {
            get
            {
                return this.applicationContextExtensionField;
            }
            set
            {
                this.applicationContextExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class ErrorInfo
    {

        private System.DateTime errorTimeStampField;

        private bool errorTimeStampFieldSpecified;

        private string errorCodeField;

        private string severityField;

        private string errorMessageTextField;

        private string friendlyErrorMessageField;

        private string vendorMessageTextField;

        private string stackTraceField;

        private string sqlStateField;

        private string serviceNameField;

        private string sourceSystemField;

        private RuleResponse[] ruleResponseField;

        private object[] errorInfoExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public System.DateTime errorTimeStamp
        {
            get
            {
                return this.errorTimeStampField;
            }
            set
            {
                this.errorTimeStampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorTimeStampSpecified
        {
            get
            {
                return this.errorTimeStampFieldSpecified;
            }
            set
            {
                this.errorTimeStampFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string errorMessageText
        {
            get
            {
                return this.errorMessageTextField;
            }
            set
            {
                this.errorMessageTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string friendlyErrorMessage
        {
            get
            {
                return this.friendlyErrorMessageField;
            }
            set
            {
                this.friendlyErrorMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string vendorMessageText
        {
            get
            {
                return this.vendorMessageTextField;
            }
            set
            {
                this.vendorMessageTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string stackTrace
        {
            get
            {
                return this.stackTraceField;
            }
            set
            {
                this.stackTraceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string sqlState
        {
            get
            {
                return this.sqlStateField;
            }
            set
            {
                this.sqlStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string serviceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string sourceSystem
        {
            get
            {
                return this.sourceSystemField;
            }
            set
            {
                this.sourceSystemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RuleResponse", Order = 10)]
        public RuleResponse[] RuleResponse
        {
            get
            {
                return this.ruleResponseField;
            }
            set
            {
                this.ruleResponseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errorInfoExtension", Order = 11)]
        public object[] errorInfoExtension
        {
            get
            {
                return this.errorInfoExtensionField;
            }
            set
            {
                this.errorInfoExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class RuleResponse
    {

        private System.DateTime timestampField;

        private bool timestampFieldSpecified;

        private string ruleDecisionField;

        private string ruleScoreField;

        private string serviceField;

        private string[] ruleScorecardField;

        private RuleResults ruleResultsField;

        private object[] ruleResponseExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified
        {
            get
            {
                return this.timestampFieldSpecified;
            }
            set
            {
                this.timestampFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ruleDecision
        {
            get
            {
                return this.ruleDecisionField;
            }
            set
            {
                this.ruleDecisionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string ruleScore
        {
            get
            {
                return this.ruleScoreField;
            }
            set
            {
                this.ruleScoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleScorecard", Order = 4)]
        public string[] ruleScorecard
        {
            get
            {
                return this.ruleScorecardField;
            }
            set
            {
                this.ruleScorecardField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public RuleResults ruleResults
        {
            get
            {
                return this.ruleResultsField;
            }
            set
            {
                this.ruleResultsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleResponseExtension", Order = 6)]
        public object[] ruleResponseExtension
        {
            get
            {
                return this.ruleResponseExtensionField;
            }
            set
            {
                this.ruleResponseExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class RuleResults
    {

        private RuleResult[] ruleResultField;

        private object[] ruleResultsExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleResult", Order = 0)]
        public RuleResult[] ruleResult
        {
            get
            {
                return this.ruleResultField;
            }
            set
            {
                this.ruleResultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleResultsExtension", Order = 1)]
        public object[] ruleResultsExtension
        {
            get
            {
                return this.ruleResultsExtensionField;
            }
            set
            {
                this.ruleResultsExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class RuleResult
    {

        private string ruleIdField;

        private string ruleDescriptionField;

        private string actionField;

        private RuleSeverity severityField;

        private bool severityFieldSpecified;

        private bool isOverridableField;

        private bool isOverridableFieldSpecified;

        private string overrideAuthorityLevelField;

        private string instanceIdField;

        private string sourceSystemField;

        private System.DateTime timestampField;

        private bool timestampFieldSpecified;

        private RuleCategory categoryField;

        private bool categoryFieldSpecified;

        private string correlationIdField;

        private RuleAttributes ruleAttributesField;

        private object[] ruleResultExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string ruleId
        {
            get
            {
                return this.ruleIdField;
            }
            set
            {
                this.ruleIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ruleDescription
        {
            get
            {
                return this.ruleDescriptionField;
            }
            set
            {
                this.ruleDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public RuleSeverity severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool severitySpecified
        {
            get
            {
                return this.severityFieldSpecified;
            }
            set
            {
                this.severityFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public bool isOverridable
        {
            get
            {
                return this.isOverridableField;
            }
            set
            {
                this.isOverridableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isOverridableSpecified
        {
            get
            {
                return this.isOverridableFieldSpecified;
            }
            set
            {
                this.isOverridableFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string overrideAuthorityLevel
        {
            get
            {
                return this.overrideAuthorityLevelField;
            }
            set
            {
                this.overrideAuthorityLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 6)]
        public string instanceId
        {
            get
            {
                return this.instanceIdField;
            }
            set
            {
                this.instanceIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string sourceSystem
        {
            get
            {
                return this.sourceSystemField;
            }
            set
            {
                this.sourceSystemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified
        {
            get
            {
                return this.timestampFieldSpecified;
            }
            set
            {
                this.timestampFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public RuleCategory category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categorySpecified
        {
            get
            {
                return this.categoryFieldSpecified;
            }
            set
            {
                this.categoryFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 10)]
        public string correlationId
        {
            get
            {
                return this.correlationIdField;
            }
            set
            {
                this.correlationIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public RuleAttributes ruleAttributes
        {
            get
            {
                return this.ruleAttributesField;
            }
            set
            {
                this.ruleAttributesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleResultExtension", Order = 12)]
        public object[] ruleResultExtension
        {
            get
            {
                return this.ruleResultExtensionField;
            }
            set
            {
                this.ruleResultExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public enum RuleSeverity
    {

        /// <remarks/>
        Informational,

        /// <remarks/>
        High,

        /// <remarks/>
        Medium,

        /// <remarks/>
        Low,

        /// <remarks/>
        Error,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public enum RuleCategory
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Product Constraint")]
        ProductConstraint,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Mandatory Data")]
        MandatoryData,

        /// <remarks/>
        Eligibility,

        /// <remarks/>
        Underwriting,

        /// <remarks/>
        Informational,

        /// <remarks/>
        Clerical,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class RuleAttributes
    {

        private RuleAttribute[] ruleattributeField;

        private object[] ruleAttributesExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleattribute", Order = 0)]
        public RuleAttribute[] ruleattribute
        {
            get
            {
                return this.ruleattributeField;
            }
            set
            {
                this.ruleattributeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleAttributesExtension", Order = 1)]
        public object[] ruleAttributesExtension
        {
            get
            {
                return this.ruleAttributesExtensionField;
            }
            set
            {
                this.ruleAttributesExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class RuleAttribute
    {

        private string[] stringRefField;

        private object[] ruleAttributeExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stringRef", Order = 0)]
        public string[] stringRef
        {
            get
            {
                return this.stringRefField;
            }
            set
            {
                this.stringRefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleAttributeExtension", Order = 1)]
        public object[] ruleAttributeExtension
        {
            get
            {
                return this.ruleAttributeExtensionField;
            }
            set
            {
                this.ruleAttributeExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class RuleResponses
    {

        private RuleResponse[] ruleResponseField;

        private object[] ruleResponsesExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleResponse", Order = 0)]
        public RuleResponse[] ruleResponse
        {
            get
            {
                return this.ruleResponseField;
            }
            set
            {
                this.ruleResponseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleResponsesExtension", Order = 1)]
        public object[] ruleResponsesExtension
        {
            get
            {
                return this.ruleResponsesExtensionField;
            }
            set
            {
                this.ruleResponsesExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_RetrieveFinancialInstitutionDetail_version2")]
    public partial class PreferenceTelephone
    {

        private string typeField;

        private string preferenceTelephoneIdentifierField;

        private string countryCodeField;

        private string areaCodeField;

        private string extensionField;

        private bool preferredField;

        private bool preferredFieldSpecified;

        private string localNumberField;

        private bool doNotCallField;

        private string prefixCodeField;

        private string displayValueField;

        private object[] preferenceTelephoneExtensionField;

        public PreferenceTelephone()
        {
            this.doNotCallField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string preferenceTelephoneIdentifier
        {
            get
            {
                return this.preferenceTelephoneIdentifierField;
            }
            set
            {
                this.preferenceTelephoneIdentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 2)]
        public string countryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 3)]
        public string areaCode
        {
            get
            {
                return this.areaCodeField;
            }
            set
            {
                this.areaCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 4)]
        public string extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public bool preferred
        {
            get
            {
                return this.preferredField;
            }
            set
            {
                this.preferredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool preferredSpecified
        {
            get
            {
                return this.preferredFieldSpecified;
            }
            set
            {
                this.preferredFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 6)]
        public string localNumber
        {
            get
            {
                return this.localNumberField;
            }
            set
            {
                this.localNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool doNotCall
        {
            get
            {
                return this.doNotCallField;
            }
            set
            {
                this.doNotCallField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string prefixCode
        {
            get
            {
                return this.prefixCodeField;
            }
            set
            {
                this.prefixCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string displayValue
        {
            get
            {
                return this.displayValueField;
            }
            set
            {
                this.displayValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("preferenceTelephoneExtension", Order = 10)]
        public object[] preferenceTelephoneExtension
        {
            get
            {
                return this.preferenceTelephoneExtensionField;
            }
            set
            {
                this.preferenceTelephoneExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_RetrieveFinancialInstitutionDetail_version2")]
    public partial class TelephoneNumbers
    {

        private PreferenceTelephone[] telephoneNumberField;

        private object[] telephoneNumbersExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("telephoneNumber", Order = 0)]
        public PreferenceTelephone[] telephoneNumber
        {
            get
            {
                return this.telephoneNumberField;
            }
            set
            {
                this.telephoneNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("telephoneNumbersExtension", Order = 1)]
        public object[] telephoneNumbersExtension
        {
            get
            {
                return this.telephoneNumbersExtensionField;
            }
            set
            {
                this.telephoneNumbersExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_RetrieveFinancialInstitutionDetail_version2")]
    public partial class PostalAddressSummary
    {

        private string cityStatePostalCodeLineField;

        private string houseNumberField;

        private string extendedStreetAddressLineField;

        private string precedingDirectionField;

        private string streetNameField;

        private string floorNumberField;

        private string cityNameField;

        private string streetSuffixField;

        private string countyNameField;

        private string postDirectionField;

        private string zipCodeField;

        private string isoCountryCodeField;

        private string isoRegionCodeField;

        private string postalBoxNumberField;

        private string streetAddressLineField;

        private string unitNumberField;

        private string typeField;

        private object[] postalAddressSummaryExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string cityStatePostalCodeLine
        {
            get
            {
                return this.cityStatePostalCodeLineField;
            }
            set
            {
                this.cityStatePostalCodeLineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string houseNumber
        {
            get
            {
                return this.houseNumberField;
            }
            set
            {
                this.houseNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string extendedStreetAddressLine
        {
            get
            {
                return this.extendedStreetAddressLineField;
            }
            set
            {
                this.extendedStreetAddressLineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string precedingDirection
        {
            get
            {
                return this.precedingDirectionField;
            }
            set
            {
                this.precedingDirectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string streetName
        {
            get
            {
                return this.streetNameField;
            }
            set
            {
                this.streetNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string floorNumber
        {
            get
            {
                return this.floorNumberField;
            }
            set
            {
                this.floorNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string cityName
        {
            get
            {
                return this.cityNameField;
            }
            set
            {
                this.cityNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string streetSuffix
        {
            get
            {
                return this.streetSuffixField;
            }
            set
            {
                this.streetSuffixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string countyName
        {
            get
            {
                return this.countyNameField;
            }
            set
            {
                this.countyNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string postDirection
        {
            get
            {
                return this.postDirectionField;
            }
            set
            {
                this.postDirectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string zipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string isoCountryCode
        {
            get
            {
                return this.isoCountryCodeField;
            }
            set
            {
                this.isoCountryCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string isoRegionCode
        {
            get
            {
                return this.isoRegionCodeField;
            }
            set
            {
                this.isoRegionCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public string postalBoxNumber
        {
            get
            {
                return this.postalBoxNumberField;
            }
            set
            {
                this.postalBoxNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public string streetAddressLine
        {
            get
            {
                return this.streetAddressLineField;
            }
            set
            {
                this.streetAddressLineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public string unitNumber
        {
            get
            {
                return this.unitNumberField;
            }
            set
            {
                this.unitNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("postalAddressSummaryExtension", Order = 17)]
        public object[] postalAddressSummaryExtension
        {
            get
            {
                return this.postalAddressSummaryExtensionField;
            }
            set
            {
                this.postalAddressSummaryExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FinancialInstitution))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_RetrieveFinancialInstitutionDetail_version2")]
    public partial class Institution
    {

        private string institutionIdentifierField;

        private string shortNameField;

        private string fullNameField;

        private PostalAddressSummary addressField;

        private TelephoneNumbers telephoneNumbersField;

        private object[] institutionExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string institutionIdentifier
        {
            get
            {
                return this.institutionIdentifierField;
            }
            set
            {
                this.institutionIdentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string shortName
        {
            get
            {
                return this.shortNameField;
            }
            set
            {
                this.shortNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string fullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public PostalAddressSummary address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public TelephoneNumbers telephoneNumbers
        {
            get
            {
                return this.telephoneNumbersField;
            }
            set
            {
                this.telephoneNumbersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("institutionExtension", Order = 5)]
        public object[] institutionExtension
        {
            get
            {
                return this.institutionExtensionField;
            }
            set
            {
                this.institutionExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_RetrieveFinancialInstitutionDetail_version2")]
    public partial class FinancialInstitution : Institution
    {

        private string aBANumberField;

        private bool aCHCapableField;

        private string aCHNumberField;

        private string routingNumberField;

        private string routingNumberTypeField;

        private string routingNumberDescriptionField;

        private string routingNumberStatusField;

        private string routingNumberStatusDescriptionField;

        private object[] financialInstitutionExtensionField;

        public FinancialInstitution()
        {
            this.aCHCapableField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string ABANumber
        {
            get
            {
                return this.aBANumberField;
            }
            set
            {
                this.aBANumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool ACHCapable
        {
            get
            {
                return this.aCHCapableField;
            }
            set
            {
                this.aCHCapableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string ACHNumber
        {
            get
            {
                return this.aCHNumberField;
            }
            set
            {
                this.aCHNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string routingNumber
        {
            get
            {
                return this.routingNumberField;
            }
            set
            {
                this.routingNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string routingNumberType
        {
            get
            {
                return this.routingNumberTypeField;
            }
            set
            {
                this.routingNumberTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string routingNumberDescription
        {
            get
            {
                return this.routingNumberDescriptionField;
            }
            set
            {
                this.routingNumberDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string routingNumberStatus
        {
            get
            {
                return this.routingNumberStatusField;
            }
            set
            {
                this.routingNumberStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string routingNumberStatusDescription
        {
            get
            {
                return this.routingNumberStatusDescriptionField;
            }
            set
            {
                this.routingNumberStatusDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("financialInstitutionExtension", Order = 8)]
        public object[] financialInstitutionExtension
        {
            get
            {
                return this.financialInstitutionExtensionField;
            }
            set
            {
                this.financialInstitutionExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_WSDL_RetrieveFinancialInstitutionDetail_version2" +
        "")]
    public partial class retrieveFinancialInstitutionDetailResponse
    {

        private ApplicationContext applicationContextField;

        private FinancialInstitution financialInstitutionField;

        private object[] messageExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ApplicationContext applicationContext
        {
            get
            {
                return this.applicationContextField;
            }
            set
            {
                this.applicationContextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public FinancialInstitution financialInstitution
        {
            get
            {
                return this.financialInstitutionField;
            }
            set
            {
                this.financialInstitutionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageExtension", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public object[] messageExtension
        {
            get
            {
                return this.messageExtensionField;
            }
            set
            {
                this.messageExtensionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RetrieveFinancialInstitutionDetailRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_WSDL_RetrieveFinancialInstitutionDetail_version2" +
            "", Order = 0)]
        public retrieveFinancialInstitutionDetailRequest retrieveFinancialInstitutionDetailRequest;

        public RetrieveFinancialInstitutionDetailRequest1()
        {
        }

        public RetrieveFinancialInstitutionDetailRequest1(retrieveFinancialInstitutionDetailRequest retrieveFinancialInstitutionDetailRequest)
        {
            this.retrieveFinancialInstitutionDetailRequest = retrieveFinancialInstitutionDetailRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class RetrieveFinancialInstitutionDetailResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_WSDL_RetrieveFinancialInstitutionDetail_version2" +
            "", Order = 0)]
        public retrieveFinancialInstitutionDetailResponse retrieveFinancialInstitutionDetailResponse;

        public RetrieveFinancialInstitutionDetailResponse1()
        {
        }

        public RetrieveFinancialInstitutionDetailResponse1(retrieveFinancialInstitutionDetailResponse retrieveFinancialInstitutionDetailResponse)
        {
            this.retrieveFinancialInstitutionDetailResponse = retrieveFinancialInstitutionDetailResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface RetrieveFinancialInstitutionDetailChannel : RetrieveFinancialInstitutionDetail, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RetrieveFinancialInstitutionDetailClient : System.ServiceModel.ClientBase<RetrieveFinancialInstitutionDetail>, RetrieveFinancialInstitutionDetail
    {

        public RetrieveFinancialInstitutionDetailClient()
        {
        }

        public RetrieveFinancialInstitutionDetailClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public RetrieveFinancialInstitutionDetailClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public RetrieveFinancialInstitutionDetailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public RetrieveFinancialInstitutionDetailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RetrieveFinancialInstitutionDetailResponse1 RetrieveFinancialInstitutionDetail.RetrieveFinancialInstitutionDetail(RetrieveFinancialInstitutionDetailRequest1 request)
        {
            return base.Channel.RetrieveFinancialInstitutionDetail(request);
        }

        public retrieveFinancialInstitutionDetailResponse RetrieveFinancialInstitutionDetail(retrieveFinancialInstitutionDetailRequest retrieveFinancialInstitutionDetailRequest)
        {
            RetrieveFinancialInstitutionDetailRequest1 inValue = new RetrieveFinancialInstitutionDetailRequest1();
            inValue.retrieveFinancialInstitutionDetailRequest = retrieveFinancialInstitutionDetailRequest;
            RetrieveFinancialInstitutionDetailResponse1 retVal = ((RetrieveFinancialInstitutionDetail)(this)).RetrieveFinancialInstitutionDetail(inValue);
            return retVal.retrieveFinancialInstitutionDetailResponse;
        }
    }
    namespace www.aaancnuit.com.aaancnu_common_version2
    {


        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
        [System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
        public partial class ErrorInfo : object, System.Xml.Serialization.IXmlSerializable
        {

            private System.Xml.XmlNode[] nodesField;

            private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ErrorInfo", "http://www.aaancnuit.com.AAANCNU_Common_version2");

            public System.Xml.XmlNode[] Nodes
            {
                get
                {
                    return this.nodesField;
                }
                set
                {
                    this.nodesField = value;
                }
            }

            public void ReadXml(System.Xml.XmlReader reader)
            {
                this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
            }

            public void WriteXml(System.Xml.XmlWriter writer)
            {
                System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
            }

            public System.Xml.Schema.XmlSchema GetSchema()
            {
                return null;
            }

            public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
            {
                System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
                return typeName;
            }
        }
    }
}