//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4234
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//PC PhaseII CH1 - Added an New Proxy class for Issue Direct payment Reversal Service.
namespace IDPReversal
{
    [assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.aaancnuit.com.AAANCNU_Common_version2", ClrNamespace = "www.aaancnuit.com.aaancnu_common_version2")]



    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_WSDL_IssueDirectPaymentReversal_version2", ConfigurationName = "IssueDirectPaymentReversal")]
    public interface IssueDirectPaymentReversal
    {

        // CODEGEN: Generating message contract since the operation IssueDirectPaymentReversal is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.aaancnuit.com.issueDirectPaymentReversal", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.aaancnuit.com.aaancnu_common_version2.ErrorInfo), Action = "http://www.aaancnuit.com.issueDirectPaymentReversal", Name = "ErrorInfo", Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ErrorInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RuleResponses))]
        IssueDirectPaymentReversalResponse1 IssueDirectPaymentReversal(IssueDirectPaymentReversalRequest1 request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_WSDL_IssueDirectPaymentReversal_version2")]
    public partial class issueDirectPaymentReversalRequest
    {

        private ApplicationContext applicationContextField;

        private string externalReferenceNumberField;

        private string agentIdentifierField;

        private string agencyField;

        private string clubField;

        private string userIdField;

        private string branchHubNumberField;

        private string districtOfficeField;

        private string deviceNumberField;

        private string sourcePhoneNumberField;

        private string reasonCodeField;

        private string paymentExternalRefNumberField;

        private string paymentReceiptNumberField;

        private object[] messageExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ApplicationContext applicationContext
        {
            get
            {
                return this.applicationContextField;
            }
            set
            {
                this.applicationContextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string externalReferenceNumber
        {
            get
            {
                return this.externalReferenceNumberField;
            }
            set
            {
                this.externalReferenceNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string agentIdentifier
        {
            get
            {
                return this.agentIdentifierField;
            }
            set
            {
                this.agentIdentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string agency
        {
            get
            {
                return this.agencyField;
            }
            set
            {
                this.agencyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string club
        {
            get
            {
                return this.clubField;
            }
            set
            {
                this.clubField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string branchHubNumber
        {
            get
            {
                return this.branchHubNumberField;
            }
            set
            {
                this.branchHubNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string districtOffice
        {
            get
            {
                return this.districtOfficeField;
            }
            set
            {
                this.districtOfficeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string deviceNumber
        {
            get
            {
                return this.deviceNumberField;
            }
            set
            {
                this.deviceNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string sourcePhoneNumber
        {
            get
            {
                return this.sourcePhoneNumberField;
            }
            set
            {
                this.sourcePhoneNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string reasonCode
        {
            get
            {
                return this.reasonCodeField;
            }
            set
            {
                this.reasonCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string paymentExternalRefNumber
        {
            get
            {
                return this.paymentExternalRefNumberField;
            }
            set
            {
                this.paymentExternalRefNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public string paymentReceiptNumber
        {
            get
            {
                return this.paymentReceiptNumberField;
            }
            set
            {
                this.paymentReceiptNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageExtension", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public object[] messageExtension
        {
            get
            {
                return this.messageExtensionField;
            }
            set
            {
                this.messageExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class ApplicationContext
    {

        private string userIdField;

        private string transactionTypeField;

        private string applicationField;

        private string subSystemField;

        private string addressField;

        private string correlationIdField;

        private object[] applicationContextExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string transactionType
        {
            get
            {
                return this.transactionTypeField;
            }
            set
            {
                this.transactionTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string subSystem
        {
            get
            {
                return this.subSystemField;
            }
            set
            {
                this.subSystemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string correlationId
        {
            get
            {
                return this.correlationIdField;
            }
            set
            {
                this.correlationIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("applicationContextExtension", Order = 6)]
        public object[] applicationContextExtension
        {
            get
            {
                return this.applicationContextExtensionField;
            }
            set
            {
                this.applicationContextExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class ErrorInfo
    {

        private System.DateTime errorTimeStampField;

        private bool errorTimeStampFieldSpecified;

        private string errorCodeField;

        private string severityField;

        private string errorMessageTextField;

        private string friendlyErrorMessageField;

        private string vendorMessageTextField;

        private string stackTraceField;

        private string sqlStateField;

        private string serviceNameField;

        private string sourceSystemField;

        private RuleResponse[] ruleResponseField;

        private object[] errorInfoExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public System.DateTime errorTimeStamp
        {
            get
            {
                return this.errorTimeStampField;
            }
            set
            {
                this.errorTimeStampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorTimeStampSpecified
        {
            get
            {
                return this.errorTimeStampFieldSpecified;
            }
            set
            {
                this.errorTimeStampFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string errorMessageText
        {
            get
            {
                return this.errorMessageTextField;
            }
            set
            {
                this.errorMessageTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string friendlyErrorMessage
        {
            get
            {
                return this.friendlyErrorMessageField;
            }
            set
            {
                this.friendlyErrorMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string vendorMessageText
        {
            get
            {
                return this.vendorMessageTextField;
            }
            set
            {
                this.vendorMessageTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string stackTrace
        {
            get
            {
                return this.stackTraceField;
            }
            set
            {
                this.stackTraceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string sqlState
        {
            get
            {
                return this.sqlStateField;
            }
            set
            {
                this.sqlStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string serviceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string sourceSystem
        {
            get
            {
                return this.sourceSystemField;
            }
            set
            {
                this.sourceSystemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RuleResponse", Order = 10)]
        public RuleResponse[] RuleResponse
        {
            get
            {
                return this.ruleResponseField;
            }
            set
            {
                this.ruleResponseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errorInfoExtension", Order = 11)]
        public object[] errorInfoExtension
        {
            get
            {
                return this.errorInfoExtensionField;
            }
            set
            {
                this.errorInfoExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class RuleResponse
    {

        private System.DateTime timestampField;

        private bool timestampFieldSpecified;

        private string ruleDecisionField;

        private string ruleScoreField;

        private string serviceField;

        private string[] ruleScorecardField;

        private RuleResults ruleResultsField;

        private object[] ruleResponseExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified
        {
            get
            {
                return this.timestampFieldSpecified;
            }
            set
            {
                this.timestampFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ruleDecision
        {
            get
            {
                return this.ruleDecisionField;
            }
            set
            {
                this.ruleDecisionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string ruleScore
        {
            get
            {
                return this.ruleScoreField;
            }
            set
            {
                this.ruleScoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleScorecard", Order = 4)]
        public string[] ruleScorecard
        {
            get
            {
                return this.ruleScorecardField;
            }
            set
            {
                this.ruleScorecardField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public RuleResults ruleResults
        {
            get
            {
                return this.ruleResultsField;
            }
            set
            {
                this.ruleResultsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleResponseExtension", Order = 6)]
        public object[] ruleResponseExtension
        {
            get
            {
                return this.ruleResponseExtensionField;
            }
            set
            {
                this.ruleResponseExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class RuleResults
    {

        private RuleResult[] ruleResultField;

        private object[] ruleResultsExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleResult", Order = 0)]
        public RuleResult[] ruleResult
        {
            get
            {
                return this.ruleResultField;
            }
            set
            {
                this.ruleResultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleResultsExtension", Order = 1)]
        public object[] ruleResultsExtension
        {
            get
            {
                return this.ruleResultsExtensionField;
            }
            set
            {
                this.ruleResultsExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class RuleResult
    {

        private string ruleIdField;

        private string ruleDescriptionField;

        private string actionField;

        private RuleSeverity severityField;

        private bool severityFieldSpecified;

        private bool isOverridableField;

        private bool isOverridableFieldSpecified;

        private string overrideAuthorityLevelField;

        private string instanceIdField;

        private string sourceSystemField;

        private System.DateTime timestampField;

        private bool timestampFieldSpecified;

        private RuleCategory categoryField;

        private bool categoryFieldSpecified;

        private string correlationIdField;

        private RuleAttributes ruleAttributesField;

        private object[] ruleResultExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string ruleId
        {
            get
            {
                return this.ruleIdField;
            }
            set
            {
                this.ruleIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string ruleDescription
        {
            get
            {
                return this.ruleDescriptionField;
            }
            set
            {
                this.ruleDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public RuleSeverity severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool severitySpecified
        {
            get
            {
                return this.severityFieldSpecified;
            }
            set
            {
                this.severityFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public bool isOverridable
        {
            get
            {
                return this.isOverridableField;
            }
            set
            {
                this.isOverridableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isOverridableSpecified
        {
            get
            {
                return this.isOverridableFieldSpecified;
            }
            set
            {
                this.isOverridableFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string overrideAuthorityLevel
        {
            get
            {
                return this.overrideAuthorityLevelField;
            }
            set
            {
                this.overrideAuthorityLevelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 6)]
        public string instanceId
        {
            get
            {
                return this.instanceIdField;
            }
            set
            {
                this.instanceIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string sourceSystem
        {
            get
            {
                return this.sourceSystemField;
            }
            set
            {
                this.sourceSystemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified
        {
            get
            {
                return this.timestampFieldSpecified;
            }
            set
            {
                this.timestampFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public RuleCategory category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categorySpecified
        {
            get
            {
                return this.categoryFieldSpecified;
            }
            set
            {
                this.categoryFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 10)]
        public string correlationId
        {
            get
            {
                return this.correlationIdField;
            }
            set
            {
                this.correlationIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public RuleAttributes ruleAttributes
        {
            get
            {
                return this.ruleAttributesField;
            }
            set
            {
                this.ruleAttributesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleResultExtension", Order = 12)]
        public object[] ruleResultExtension
        {
            get
            {
                return this.ruleResultExtensionField;
            }
            set
            {
                this.ruleResultExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public enum RuleSeverity
    {

        /// <remarks/>
        Informational,

        /// <remarks/>
        High,

        /// <remarks/>
        Medium,

        /// <remarks/>
        Low,

        /// <remarks/>
        Error,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public enum RuleCategory
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Product Constraint")]
        ProductConstraint,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Mandatory Data")]
        MandatoryData,

        /// <remarks/>
        Eligibility,

        /// <remarks/>
        Underwriting,

        /// <remarks/>
        Informational,

        /// <remarks/>
        Clerical,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class RuleAttributes
    {

        private RuleAttribute[] ruleattributeField;

        private object[] ruleAttributesExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleattribute", Order = 0)]
        public RuleAttribute[] ruleattribute
        {
            get
            {
                return this.ruleattributeField;
            }
            set
            {
                this.ruleattributeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleAttributesExtension", Order = 1)]
        public object[] ruleAttributesExtension
        {
            get
            {
                return this.ruleAttributesExtensionField;
            }
            set
            {
                this.ruleAttributesExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class RuleAttribute
    {

        private string[] stringRefField;

        private object[] ruleAttributeExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stringRef", Order = 0)]
        public string[] stringRef
        {
            get
            {
                return this.stringRefField;
            }
            set
            {
                this.stringRefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleAttributeExtension", Order = 1)]
        public object[] ruleAttributeExtension
        {
            get
            {
                return this.ruleAttributeExtensionField;
            }
            set
            {
                this.ruleAttributeExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_Common_version2")]
    public partial class RuleResponses
    {

        private RuleResponse[] ruleResponseField;

        private object[] ruleResponsesExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleResponse", Order = 0)]
        public RuleResponse[] ruleResponse
        {
            get
            {
                return this.ruleResponseField;
            }
            set
            {
                this.ruleResponseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ruleResponsesExtension", Order = 1)]
        public object[] ruleResponsesExtension
        {
            get
            {
                return this.ruleResponsesExtensionField;
            }
            set
            {
                this.ruleResponsesExtensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_WSDL_IssueDirectPaymentReversal_version2")]
    public partial class issueDirectPaymentReversalResponse
    {

        private ApplicationContext applicationContextField;

        private string externalReferenceNumberField;

        private string receiptNumberField;

        private string statusField;

        private string statusDescriptionField;

        private System.DateTime paymentReversalDateTimeField;

        private bool paymentReversalDateTimeFieldSpecified;

        private string paymentReceiptNumberField;

        private object[] messageExtensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ApplicationContext applicationContext
        {
            get
            {
                return this.applicationContextField;
            }
            set
            {
                this.applicationContextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string externalReferenceNumber
        {
            get
            {
                return this.externalReferenceNumberField;
            }
            set
            {
                this.externalReferenceNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string receiptNumber
        {
            get
            {
                return this.receiptNumberField;
            }
            set
            {
                this.receiptNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string statusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public System.DateTime paymentReversalDateTime
        {
            get
            {
                return this.paymentReversalDateTimeField;
            }
            set
            {
                this.paymentReversalDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentReversalDateTimeSpecified
        {
            get
            {
                return this.paymentReversalDateTimeFieldSpecified;
            }
            set
            {
                this.paymentReversalDateTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string paymentReceiptNumber
        {
            get
            {
                return this.paymentReceiptNumberField;
            }
            set
            {
                this.paymentReceiptNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageExtension", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public object[] messageExtension
        {
            get
            {
                return this.messageExtensionField;
            }
            set
            {
                this.messageExtensionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class IssueDirectPaymentReversalRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_WSDL_IssueDirectPaymentReversal_version2", Order = 0)]
        public issueDirectPaymentReversalRequest issueDirectPaymentReversalRequest;

        public IssueDirectPaymentReversalRequest1()
        {
        }

        public IssueDirectPaymentReversalRequest1(issueDirectPaymentReversalRequest issueDirectPaymentReversalRequest)
        {
            this.issueDirectPaymentReversalRequest = issueDirectPaymentReversalRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class IssueDirectPaymentReversalResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.aaancnuit.com.AAANCNU_WSDL_IssueDirectPaymentReversal_version2", Order = 0)]
        public issueDirectPaymentReversalResponse issueDirectPaymentReversalResponse;

        public IssueDirectPaymentReversalResponse1()
        {
        }

        public IssueDirectPaymentReversalResponse1(issueDirectPaymentReversalResponse issueDirectPaymentReversalResponse)
        {
            this.issueDirectPaymentReversalResponse = issueDirectPaymentReversalResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IssueDirectPaymentReversalChannel : IssueDirectPaymentReversal, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class IssueDirectPaymentReversalClient : System.ServiceModel.ClientBase<IssueDirectPaymentReversal>, IssueDirectPaymentReversal
    {

        public IssueDirectPaymentReversalClient()
        {
        }

        public IssueDirectPaymentReversalClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public IssueDirectPaymentReversalClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public IssueDirectPaymentReversalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public IssueDirectPaymentReversalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IssueDirectPaymentReversalResponse1 IssueDirectPaymentReversal.IssueDirectPaymentReversal(IssueDirectPaymentReversalRequest1 request)
        {
            return base.Channel.IssueDirectPaymentReversal(request);
        }

        public issueDirectPaymentReversalResponse IssueDirectPaymentReversal(issueDirectPaymentReversalRequest issueDirectPaymentReversalRequest)
        {
            IssueDirectPaymentReversalRequest1 inValue = new IssueDirectPaymentReversalRequest1();
            inValue.issueDirectPaymentReversalRequest = issueDirectPaymentReversalRequest;
            IssueDirectPaymentReversalResponse1 retVal = ((IssueDirectPaymentReversal)(this)).IssueDirectPaymentReversal(inValue);
            return retVal.issueDirectPaymentReversalResponse;
        }
    }
    namespace www.aaancnuit.com.aaancnu_common_version2
    {


        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
        [System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
        public partial class ErrorInfo : object, System.Xml.Serialization.IXmlSerializable
        {

            private System.Xml.XmlNode[] nodesField;

            private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ErrorInfo", "http://www.aaancnuit.com.AAANCNU_Common_version2");

            public System.Xml.XmlNode[] Nodes
            {
                get
                {
                    return this.nodesField;
                }
                set
                {
                    this.nodesField = value;
                }
            }

            public void ReadXml(System.Xml.XmlReader reader)
            {
                this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
            }

            public void WriteXml(System.Xml.XmlWriter writer)
            {
                System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
            }

            public System.Xml.Schema.XmlSchema GetSchema()
            {
                return null;
            }

            public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
            {
                System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
                return typeName;
            }
        }
    }
}