//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4216
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4216.
// 
#pragma warning disable 1591

namespace CSAAWeb.ArcSightReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RecordApplicationEventAsyncSOAPPortBinding", Namespace="http://www.aaancnuit.com.AAANCNU_WSDL_RecordApplicationEventAsync_version1")]
    public partial class RecordApplicationEventAsyncService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RecordApplicationEventAsyncOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RecordApplicationEventAsyncService() {
            this.Url = global::CSAAWeb.Properties.Settings.Default.CSAAWeb_WebReference_RecordApplicationEventAsyncService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RecordApplicationEventAsyncCompletedEventHandler RecordApplicationEventAsyncCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.aaancnuit.com.recordApplicationEventAsync", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void RecordApplicationEventAsync([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.aaancnuit.com.AAANCNU_WSDL_RecordApplicationEventAsync_version1")] recordApplicationEventAsyncRequest recordApplicationEventAsyncRequest) {
            this.Invoke("RecordApplicationEventAsync", new object[] {
                        recordApplicationEventAsyncRequest});
        }
        
        /// <remarks/>
        public void RecordApplicationEventAsyncAsync(recordApplicationEventAsyncRequest recordApplicationEventAsyncRequest) {
            this.RecordApplicationEventAsyncAsync(recordApplicationEventAsyncRequest, null);
        }
        
        /// <remarks/>
        public void RecordApplicationEventAsyncAsync(recordApplicationEventAsyncRequest recordApplicationEventAsyncRequest, object userState) {
            if ((this.RecordApplicationEventAsyncOperationCompleted == null)) {
                this.RecordApplicationEventAsyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecordApplicationEventAsyncOperationCompleted);
            }
            this.InvokeAsync("RecordApplicationEventAsync", new object[] {
                        recordApplicationEventAsyncRequest}, this.RecordApplicationEventAsyncOperationCompleted, userState);
        }
        
        private void OnRecordApplicationEventAsyncOperationCompleted(object arg) {
            if ((this.RecordApplicationEventAsyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecordApplicationEventAsyncCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aaancnuit.com.AAANCNU_WSDL_RecordApplicationEventAsync_version1")]
    public partial class recordApplicationEventAsyncRequest {
        
        private ApplicationContext applicationContextField;
        
        private ServiceOptions optionsField;
        
        private RecordApplicationEventAsync_Operations operationsField;
        
        private ExtensionArea[] filtersField;
        
        private ExtensionArea[] technicalCriteriaField;
        
        private string logLevelField;
        
        private string requestorNameField;
        
        private recordApplicationEventAsync_choice recordApplicationEventAsync_choiceField;
        
        private ExtensionArea[] recordApplicationEventAsyncRequestExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApplicationContext applicationContext {
            get {
                return this.applicationContextField;
            }
            set {
                this.applicationContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceOptions options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecordApplicationEventAsync_Operations operations {
            get {
                return this.operationsField;
            }
            set {
                this.operationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("recordApplicationEventAsync_ResponseFilterExtension", Namespace="http://www.aaancnuit.com.AAANCNU_RecordApplicationEventAsync_version1", IsNullable=false)]
        public ExtensionArea[] filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("recordApplicationEventAsync_TechnicalCriteriaExtension", Namespace="http://www.aaancnuit.com.AAANCNU_RecordApplicationEventAsync_version1", IsNullable=false)]
        public ExtensionArea[] technicalCriteria {
            get {
                return this.technicalCriteriaField;
            }
            set {
                this.technicalCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string logLevel {
            get {
                return this.logLevelField;
            }
            set {
                this.logLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string requestorName {
            get {
                return this.requestorNameField;
            }
            set {
                this.requestorNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public recordApplicationEventAsync_choice recordApplicationEventAsync_choice {
            get {
                return this.recordApplicationEventAsync_choiceField;
            }
            set {
                this.recordApplicationEventAsync_choiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recordApplicationEventAsyncRequestExtension", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ExtensionArea[] recordApplicationEventAsyncRequestExtension {
            get {
                return this.recordApplicationEventAsyncRequestExtensionField;
            }
            set {
                this.recordApplicationEventAsyncRequestExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aaancnuit.com.AAANCNU_Common_version1")]
    public partial class ApplicationContext {
        
        private string userIdField;
        
        private string transactionTypeField;
        
        private string applicationField;
        
        private string subSystemField;
        
        private string addressField;
        
        private string correlationIdField;
        
        private ExtensionArea[] applicationContextExtensionField;
        
        /// <remarks/>
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
            }
        }
        
        /// <remarks/>
        public string subSystem {
            get {
                return this.subSystemField;
            }
            set {
                this.subSystemField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string correlationId {
            get {
                return this.correlationIdField;
            }
            set {
                this.correlationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("applicationContextExtension", IsNullable=true)]
        public ExtensionArea[] applicationContextExtension {
            get {
                return this.applicationContextExtensionField;
            }
            set {
                this.applicationContextExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aaancnuit.com.AAANCNU_Common_version1")]
    public partial class ExtensionArea {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aaancnuit.com.AAANCNU_ApplicationEvent_version1")]
    public partial class ApplicationMessage {
        
        private string versionField;
        
        private string applicationField;
        
        private string subsystemField;
        
        private string moduleField;
        
        private string userIdField;
        
        private string addressField;
        
        private string correlationIdField;
        
        private string errorCodeField;
        
        private string detailedMessageField;
        
        private ExtensionArea[] applicationMessageExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
            }
        }
        
        /// <remarks/>
        public string subsystem {
            get {
                return this.subsystemField;
            }
            set {
                this.subsystemField = value;
            }
        }
        
        /// <remarks/>
        public string module {
            get {
                return this.moduleField;
            }
            set {
                this.moduleField = value;
            }
        }
        
        /// <remarks/>
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string correlationId {
            get {
                return this.correlationIdField;
            }
            set {
                this.correlationIdField = value;
            }
        }
        
        /// <remarks/>
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string detailedMessage {
            get {
                return this.detailedMessageField;
            }
            set {
                this.detailedMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("applicationMessageExtension", IsNullable=true)]
        public ExtensionArea[] applicationMessageExtension {
            get {
                return this.applicationMessageExtensionField;
            }
            set {
                this.applicationMessageExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aaancnuit.com.AAANCNU_ApplicationEvent_version1")]
    public partial class ApplicationMessageExtension {
        
        private System.DateTime timestampField;
        
        private ApplicationMessage eventMessageField;
        
        private ExtensionArea[] applicationMessageExtensionExtensionField;
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public ApplicationMessage eventMessage {
            get {
                return this.eventMessageField;
            }
            set {
                this.eventMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("applicationMessageExtensionExtension", IsNullable=true)]
        public ExtensionArea[] applicationMessageExtensionExtension {
            get {
                return this.applicationMessageExtensionExtensionField;
            }
            set {
                this.applicationMessageExtensionExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aaancnuit.com.AAANCNU_Common_version1")]
    public partial class ObjectProperty {
        
        private string nameField;
        
        private string valueField;
        
        private ExtensionArea[] objectPropertyExtensionField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objectPropertyExtension", IsNullable=true)]
        public ExtensionArea[] objectPropertyExtension {
            get {
                return this.objectPropertyExtensionField;
            }
            set {
                this.objectPropertyExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aaancnuit.com.AAANCNU_ApplicationEvent_version1")]
    public partial class CEFEvent {
        
        private string versionField;
        
        private string deviceVendorField;
        
        private string deviceProductField;
        
        private string deviceVersionField;
        
        private string signatureIdField;
        
        private string nameField;
        
        private string severityField;
        
        private ObjectProperty[] extensionField;
        
        private ExtensionArea[] cEFEventExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string deviceVendor {
            get {
                return this.deviceVendorField;
            }
            set {
                this.deviceVendorField = value;
            }
        }
        
        /// <remarks/>
        public string deviceProduct {
            get {
                return this.deviceProductField;
            }
            set {
                this.deviceProductField = value;
            }
        }
        
        /// <remarks/>
        public string deviceVersion {
            get {
                return this.deviceVersionField;
            }
            set {
                this.deviceVersionField = value;
            }
        }
        
        /// <remarks/>
        public string signatureId {
            get {
                return this.signatureIdField;
            }
            set {
                this.signatureIdField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extension", IsNullable=true)]
        public ObjectProperty[] extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cEFEventExtension")]
        public ExtensionArea[] cEFEventExtension {
            get {
                return this.cEFEventExtensionField;
            }
            set {
                this.cEFEventExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aaancnuit.com.AAANCNU_WSDL_RecordApplicationEventAsync_version1")]
    public partial class recordApplicationEventAsync_choice {
        
        private CEFEvent eventField;
        
        private ApplicationMessageExtension messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CEFEvent @event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ApplicationMessageExtension message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aaancnuit.com.AAANCNU_RecordApplicationEventAsync_version1")]
    public partial class RecordApplicationEventAsync_Operations {
        
        private string minorField;
        
        private RecordApplicationEventAsync_OperationType operationField;
        
        private ExtensionArea[] recordApplicationEventAsync_OperationsExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string minor {
            get {
                return this.minorField;
            }
            set {
                this.minorField = value;
            }
        }
        
        /// <remarks/>
        public RecordApplicationEventAsync_OperationType operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recordApplicationEventAsync_OperationsExtension")]
        public ExtensionArea[] recordApplicationEventAsync_OperationsExtension {
            get {
                return this.recordApplicationEventAsync_OperationsExtensionField;
            }
            set {
                this.recordApplicationEventAsync_OperationsExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aaancnuit.com.AAANCNU_RecordApplicationEventAsync_version1")]
    public enum RecordApplicationEventAsync_OperationType {
        
        /// <remarks/>
        Record,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aaancnuit.com.AAANCNU_Common_version1")]
    public partial class ResponseSort {
        
        private string sortByField;
        
        private SortDirection sortDirectionField;
        
        private ExtensionArea[] responseSortExtensionField;
        
        public ResponseSort() {
            this.sortDirectionField = SortDirection.Ascending;
        }
        
        /// <remarks/>
        public string sortBy {
            get {
                return this.sortByField;
            }
            set {
                this.sortByField = value;
            }
        }
        
        /// <remarks/>
        public SortDirection sortDirection {
            get {
                return this.sortDirectionField;
            }
            set {
                this.sortDirectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("responseSortExtension", IsNullable=true)]
        public ExtensionArea[] responseSortExtension {
            get {
                return this.responseSortExtensionField;
            }
            set {
                this.responseSortExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aaancnuit.com.AAANCNU_Common_version1")]
    public enum SortDirection {
        
        /// <remarks/>
        Descending,
        
        /// <remarks/>
        Ascending,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.aaancnuit.com.AAANCNU_Common_version1")]
    public partial class ServiceOptions {
        
        private bool echoBackRequestField;
        
        private string startPaginationInstanceField;
        
        private string maximumReturnedInstancesField;
        
        private ResponseSort[] serviceResponseSortField;
        
        private ExtensionArea[] serviceOptionsExtensionField;
        
        public ServiceOptions() {
            this.echoBackRequestField = false;
            this.maximumReturnedInstancesField = "50";
        }
        
        /// <remarks/>
        public bool echoBackRequest {
            get {
                return this.echoBackRequestField;
            }
            set {
                this.echoBackRequestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string startPaginationInstance {
            get {
                return this.startPaginationInstanceField;
            }
            set {
                this.startPaginationInstanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("50")]
        public string maximumReturnedInstances {
            get {
                return this.maximumReturnedInstancesField;
            }
            set {
                this.maximumReturnedInstancesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceResponseSort", IsNullable=true)]
        public ResponseSort[] serviceResponseSort {
            get {
                return this.serviceResponseSortField;
            }
            set {
                this.serviceResponseSortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceOptionsExtension", IsNullable=true)]
        public ExtensionArea[] serviceOptionsExtension {
            get {
                return this.serviceOptionsExtensionField;
            }
            set {
                this.serviceOptionsExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void RecordApplicationEventAsyncCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591